name: Deploy devnet

on:
  pull_request_target:
    branches:
      - develop

jobs:
  run_if:
    if: startsWith(github.head_ref, 'feature') ||  startsWith(github.head_ref, 'fix')
    name: Deploy on PR 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: check out trigger branch
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}

      # - name: check envs
      #   run: | 
      #     echo ${{ github.head_ref }}
      #     echo ${{ github.repository }}
      #     echo ${{ github.ref_name }}
      #     echo ${{ github.sha }}

      - name: Record branch env
        id: branch
        run: |
          echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          # echo $repo
          # echo $branch
          # echo $commit

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Determine Docker Image Name
        id: image
        run: |
            echo "name=xinfinorg/xdcsubnets:${{ steps.branch.outputs.branch }}" >> $GITHUB_OUTPUT
        

      - name: Build and push image
        run: |
          docker build . --file docker/Dockerfile --tag ${{ steps.image.outputs.name }}
          docker push ${{ steps.image.outputs.name }}

      - name: trigger deploy workflow
        id: trigger_deploy
        run: |
          echo "RESPONSE_CODE=$( \
          curl -L \
          -o response.txt \
          -w %{response_code} \
          -s \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CICD_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/hash-laboratories-au/xinfin-script/actions/workflows/subnet-deploy.yaml/dispatches \
          -d '{"ref":"test-ansible", "inputs":{"caller_repo": "${{ steps.branch.outputs.repo }}", "caller_ref": "${{ steps.branch.outputs.branch }}", "caller_sha": "${{ steps.branch.outputs.commit }}"}}' \
          )" >> $GITHUB_ENV

      - name: Check response fail or success
        run: |
          cat response.txt
          echo "RESPONSE_CODE=${{ env.RESPONSE_CODE }}"
          if [ ${{ env.RESPONSE_CODE }} != 204 ]
          then
            exit 1
          fi
