name: check functionality

on:
  pull_request_target:
    branches:
      - develop


jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: check out trigger branch
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
          git checkout pr-branch

      - name: test
        run: echo abc


      - name: test2
        run: cat example_file