name: check functionality

on:
  pull_request:
    branches:
      - feature**
      - fix**


jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: test
        run: echo abc

      - name: test2
        run: cat example_file